//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework_prezentacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAMOCHODY
    {
        public decimal ID_SAMOCHOD { get; set; }
        public string MARKA { get; set; }
        public decimal ROK_PRODUKCJI { get; set; }
    }
}
